"""
gridworld.py — a small, recurring, fully-observable maze for the CARMA Phase-1 demo.

Why a maze: it is the simplest environment that (a) recurs across episodes (so a
*memory* of past experience can pay off) and (b) has a long enough solution path
that a plain reinforcement-learning agent is slow to learn — which is exactly the
gap an episodic memory closes.

The maze is generated by a seeded recursive-backtracker, so it is IDENTICAL on every
run (reproducible). Traps are penalty tiles placed OFF the shortest path, so a good
agent should learn to avoid them — "repeated mistakes" = how often it steps on a trap.

No external dependencies beyond numpy.
"""

from collections import deque
import numpy as np

# Actions: 0=up, 1=down, 2=left, 3=right
ACTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]
ACTION_NAMES = ["UP", "DOWN", "LEFT", "RIGHT"]


def _generate_maze(n_cells: int, rng: np.random.Generator) -> np.ndarray:
    """Recursive-backtracker perfect maze. Returns a (size x size) array, True=wall."""
    size = 2 * n_cells + 1
    wall = np.ones((size, size), dtype=bool)
    start = (1, 1)
    wall[start] = False
    stack = [start]
    while stack:
        r, c = stack[-1]
        neighbours = []
        for dr, dc in [(-2, 0), (2, 0), (0, -2), (0, 2)]:
            nr, nc = r + dr, c + dc
            if 1 <= nr < size - 1 and 1 <= nc < size - 1 and wall[nr, nc]:
                neighbours.append((nr, nc, dr, dc))
        if not neighbours:
            stack.pop()
            continue
        nr, nc, dr, dc = neighbours[rng.integers(len(neighbours))]
        wall[r + dr // 2, c + dc // 2] = False  # knock down the wall between
        wall[nr, nc] = False
        stack.append((nr, nc))
    return wall


class GridWorld:
    """Fully-observable maze: the tabular learner uses the true (row,col) state and
    the autoencoder encodes a whole-maze observation (see observation()). An
    egocentric, partially-observable view + an LSTM is the planned Phase-2 study."""

    def __init__(self, n_cells: int = 5, n_traps: int = 4,
                 step_penalty: float = 0.01, trap_penalty: float = 0.5,
                 goal_reward: float = 1.0, max_steps: int = 200, seed: int = 0,
                 random_start: bool = False, episode_seed: int = 0, braid: float = 0.0,
                 trap_terminal: bool = False):
        rng = np.random.default_rng(seed)
        self.random_start = random_start
        self.start_rng = np.random.default_rng(episode_seed)
        self.wall = _generate_maze(n_cells, rng)
        self.size = self.wall.shape[0]
        if braid > 0.0:
            self._braid(rng, braid)   # add loops -> redundant routes (default off; Phase-1 mazes are perfect)
        self.start = (1, 1)
        self.goal = (self.size - 2, self.size - 2)
        self.step_penalty = step_penalty
        self.trap_penalty = trap_penalty
        self.goal_reward = goal_reward
        self.max_steps = max_steps
        self.trap_terminal = trap_terminal   # if True, entering a trap ends the episode (catastrophic hazard)

        # shortest path (for trap placement + an "optimal length" reference)
        self.path = self._bfs(self.start, self.goal)
        assert self.path is not None, "maze is unsolvable — bad seed"
        self.optimal_len = len(self.path) - 1

        # place traps on free cells that are NOT on the shortest path
        free = [(r, c) for r in range(self.size) for c in range(self.size)
                if not self.wall[r, c] and (r, c) not in set(self.path)
                and (r, c) not in (self.start, self.goal)]
        rng.shuffle(free)
        self.traps = set(free[:n_traps])

        # cells the agent may start from (any free, non-goal cell) when random_start
        self.free_starts = [(r, c) for r in range(self.size) for c in range(self.size)
                            if not self.wall[r, c] and (r, c) != self.goal
                            and (r, c) not in self.traps]

        self.agent = self.start
        self.steps = 0

    def _bfs(self, src, dst):
        q = deque([src]); prev = {src: None}
        while q:
            cur = q.popleft()
            if cur == dst:
                path = []
                while cur is not None:
                    path.append(cur); cur = prev[cur]
                return path[::-1]
            r, c = cur
            for dr, dc in ACTIONS:
                nr, nc = r + dr, c + dc
                if 0 <= nr < self.size and 0 <= nc < self.size \
                        and not self.wall[nr, nc] and (nr, nc) not in prev:
                    prev[(nr, nc)] = cur; q.append((nr, nc))
        return None

    def _braid(self, rng, p):
        """Knock down a fraction `p` of interior walls that border >=2 open cells, turning
        the perfect maze into a braided one with loops / redundant routes — so safe detours
        around a hazard can exist (used only by the safety-gate study)."""
        size = self.size
        for r in range(1, size - 1):
            for c in range(1, size - 1):
                if not self.wall[r, c]:
                    continue
                open_nb = sum(not self.wall[r + dr, c + dc] for dr, dc in ACTIONS)
                if open_nb >= 2 and rng.random() < p:
                    self.wall[r, c] = False

    def reset(self):
        if self.random_start:
            self.agent = self.free_starts[self.start_rng.integers(len(self.free_starts))]
        else:
            self.agent = self.start
        self.steps = 0
        return self.state(), self.observation()

    def state(self):
        """True discrete state used by the tabular Q-learner."""
        return self.agent

    def observation(self):
        """Whole-maze view as 4 channels (wall, goal, trap, agent), flattened.

        The walls/goal/traps channels are constant; only the agent channel moves, so
        the autoencoder learns a compact latent that *identifies the agent's situation*.
        That latent is the episodic-memory key — recall by it is meaningful (no
        perceptual aliasing), which is what makes the memory help rather than hurt.
        (A local egocentric view + an LSTM to disambiguate is the Phase-2 study.)"""
        s = self.size
        wall = self.wall.astype(np.float32).ravel()
        goal = np.zeros(s * s, dtype=np.float32); goal[self.goal[0] * s + self.goal[1]] = 1.0
        trap = np.zeros(s * s, dtype=np.float32)
        for (tr, tc) in self.traps:
            trap[tr * s + tc] = 1.0
        agent = np.zeros(s * s, dtype=np.float32); agent[self.agent[0] * s + self.agent[1]] = 1.0
        return np.concatenate([wall, goal, trap, agent])

    @property
    def obs_dim(self):
        return 4 * self.size * self.size

    def step(self, action: int):
        dr, dc = ACTIONS[action]
        r, c = self.agent
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size and not self.wall[nr, nc]:
            self.agent = (nr, nc)  # else bump into wall, stay put
        self.steps += 1

        reward = -self.step_penalty
        hit_trap = self.agent in self.traps
        if hit_trap:
            reward -= self.trap_penalty
        done = self.agent == self.goal
        if done:
            reward += self.goal_reward
        trap_end = hit_trap and self.trap_terminal       # catastrophic hazard ends the episode
        truncated = self.steps >= self.max_steps
        info = {"hit_trap": hit_trap, "at_goal": done}
        return self.state(), self.observation(), reward, (done or truncated or trap_end), info
